new-object -typename psobject -prop @{
    "anchor-EmployeeID|string" = ""
    "objectclass|string" = "user"
    "FirstName|string" = ""
    "PreferredName|string" = ""
    "MiddleName|string" = ""
    "LastName|string" = ""
    "DateOfBirth|string" = ""
    "Title|string" = ""
    "DisplayName|string" = ""
    "Department|string" = ""
    "JobTitle|string" = ""
    "EmployeeType|string" = ""
    "StartDate|string" = ""
    "EndDate|string" = ""
}